//auth action type
export const SUCCESS_SIGN_UP='SUCCESS_SIGN_UP';
export const SUCCESS_LOGIN='SUCCESS_LOGIN';
export const SUCCESS_LOGOUT='SUCCESS_LOGOUT';
export const SET_USER='SET_USER';

//Products action type
export const ADD_PRODUCTS_LIST='ADD_PRODUCTS';
export const ADD_PRODUCTS_TO_LIST='ADD_PRODUCTS_TO_LIST';
export const UPDATE_PRODUCTS_TO_LIST='UPDATE_PRODUCTS_TO_LIST';
export const ADD_CURRENT_PRODUCTS='ADD_CURRENT_PRODUCTS';
export const SHOW_PRODUCT_FORM='SHOW_PRODUCT_FORM';